### ISSUE TITLE
Serializing an SPath

### ISSUE THREAD

**Issue by lemomar** [jamesporter/solandra-flutter#5]
Hi, thanks for this amazing package!

I am currently building a pixel art app(web preview available at bitwise.momar.me) and I am currently facing a major roadblock.

Now that my app is almost done, I need a way to save the data and come back to it later on. The problem is: I'm using Path objects to represent drawings and they can't be serialized. I could keep track of all points needed to draw the path but that doesn't scale well as the canvas size grows.
I'm considering switch to using this package, but is there any way to serialize a SPath?

Thanks in advance!

**Comment by jamesporter** [comment]
I don't think Solandra is likely to be a good choice for a pixel art app. It is mostly about drawing vector-ish graphics from relatively concise code.

If you wanted to use it like this, I'd try and come up with a model (in code) that is serialisable and drawable by Solandra. But I'd have assumed for pixel art something lower level would be better (though I'm not really sure of the best approach if you wanted to support things like undo/redo).

**Comment by lemomar** [comment]
Thanks for the swift response James, I'll look into it then!
